title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/favicon.ico"

url: https://tips.fat-tails.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
