title: fat-tails.io tips
description: Forensic understanding of root causes in project failure lead to improved overall success rates.
remote_theme: just-the-docs/just-the-docs

# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tips.fat-tails.io" # fat-tails.io base hostname
repository: fat-tails-io/fat-tails.github.io # for github-metadata

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/fat-tails-favicon-32x32.png"

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/fat-tails.png"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
